prune_ratios:
  module_list.0.Conv2d.weight:
    0.1
  module_list.1.Conv2d.weight:
    0.3
  module_list.2.Conv2d.weight:
    0.1
  module_list.3.Conv2d.weight:
    0.4
  module_list.5.Conv2d.weight:
    0.4
  module_list.6.Conv2d.weight:
    0.4
  module_list.7.Conv2d.weight:
    0.4
  module_list.9.Conv2d.weight:
    0.4
  module_list.10.Conv2d.weight:
    0.4
  module_list.12.Conv2d.weight:
    0.5
  module_list.13.Conv2d.weight:
    0.5
  module_list.14.Conv2d.weight:
    0.5
  module_list.16.Conv2d.weight:
    0.5
  module_list.17.Conv2d.weight:
    0.5
  module_list.19.Conv2d.weight:
    0.5
  module_list.20.Conv2d.weight:
    0.5
  module_list.22.Conv2d.weight:
    0.5
  module_list.23.Conv2d.weight:
    0.5
  module_list.25.Conv2d.weight:
    0.5
  module_list.26.Conv2d.weight:
    0.5
  module_list.28.Conv2d.weight:
    0.5
  module_list.29.Conv2d.weight:
    0.5
  module_list.31.Conv2d.weight:
    0.5
  module_list.32.Conv2d.weight:
    0.5
  module_list.34.Conv2d.weight:
    0.5
  module_list.35.Conv2d.weight:
    0.5
  module_list.37.Conv2d.weight:
    0.6
  module_list.38.Conv2d.weight:
    0.6
  module_list.39.Conv2d.weight:
    0.6
  module_list.41.Conv2d.weight:
    0.6
  module_list.42.Conv2d.weight:
    0.6
  module_list.44.Conv2d.weight:
    0.6
  module_list.45.Conv2d.weight:
    0.6
  module_list.47.Conv2d.weight:
    0.6
  module_list.48.Conv2d.weight:
    0.6
  module_list.50.Conv2d.weight:
    0.6
  module_list.51.Conv2d.weight:
    0.6
  module_list.53.Conv2d.weight:
    0.6
  module_list.54.Conv2d.weight:
    0.6
  module_list.56.Conv2d.weight:
    0.7
  module_list.57.Conv2d.weight:
    0.7
  module_list.59.Conv2d.weight:
    0.7
  module_list.60.Conv2d.weight:
    0.7
  module_list.62.Conv2d.weight:
    0.7
  module_list.63.Conv2d.weight:
    0.7
  module_list.64.Conv2d.weight:
    0.7
  module_list.66.Conv2d.weight:
    0.7
  module_list.67.Conv2d.weight:
    0.7
  module_list.69.Conv2d.weight:
    0.7
  module_list.70.Conv2d.weight:
    0.7
  module_list.72.Conv2d.weight:
    0.7
  module_list.73.Conv2d.weight:
    0.7
  module_list.75.Conv2d.weight:
    0.4
  module_list.76.Conv2d.weight:
    0.4
  module_list.77.Conv2d.weight:
    0.4
  module_list.84.Conv2d.weight:
    0.3
  module_list.85.Conv2d.weight:
    0.3
  module_list.86.Conv2d.weight:
    0.3
  module_list.87.Conv2d.weight:
    0.3
  module_list.88.Conv2d.weight:
    0.0
  module_list.91.Conv2d.weight:
    0.2
  module_list.94.Conv2d.weight:
    0.4
  module_list.95.Conv2d.weight:
    0.4
  module_list.96.Conv2d.weight:
    0.4
  module_list.97.Conv2d.weight:
    0.4
  module_list.98.Conv2d.weight:
    0.4
  module_list.99.Conv2d.weight:
    0.3
  module_list.100.Conv2d.weight:
    0.0
  module_list.103.Conv2d.weight:
    0.2
  module_list.106.Conv2d.weight:
    0.4
  module_list.107.Conv2d.weight:
    0.4
  module_list.108.Conv2d.weight:
    0.4
  module_list.109.Conv2d.weight:
    0.4
  module_list.110.Conv2d.weight:
    0.4
  module_list.111.Conv2d.weight:
    0.4
  module_list.112.Conv2d.weight:
    0.0
